version: '3.8'

# Maintainer: sandoval.morales.emmanuel@gmail.com
# Application: Express MongoDB CRUD - Development Environment

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: express-mongodb-api-dev
    ports:
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://MongoBD_magnettax:006ceb36e25f246f3638520c23670036eb899e96@e10gq.h.filess.io:27018/MongoBD_magnettax
      - PORT=3001
      - NODE_ENV=development
      - API_VERSION=v1
      - RATE_LIMIT_WINDOW_MS=900000
      - RATE_LIMIT_MAX=100
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json:ro
      - ./package-lock.json:/app/package-lock.json:ro
      - /app/node_modules
    restart: unless-stopped
    networks:
      - app-network-dev
    command: npm run dev

networks:
  app-network-dev:
    driver: bridge